### ISSUE TITLE
project chrashes on heroku

### ISSUE THREAD

**Issue by RoelofWobben** [arielj/font-awesome-sample-app#2]
When I try to run this example it chrash with this in the logs : 

```
 from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
2021-10-19T17:06:46.243430+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
2021-10-19T17:06:46.243432+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2021-10-19T17:06:46.243440+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
2021-10-19T17:06:46.243441+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
2021-10-19T17:06:46.243443+00:00 app[web.1]: from bin/rails:5:in `<main>'
2021-10-19T17:06:46.381448+00:00 heroku[web.1]: Process exited with status 1
2021-10-19T17:06:46.443374+00:00 heroku[web.1]: State changed from starting to crashed
2021-10-19T17:07:02.783192+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=young-badlands-22721.herokuapp.com request_id=5264cffa-a17b-4971-87ba-b5776208eb47 fwd="82.74.147.203" dyno= connect= service= status=503 bytes= protocol=https
2021-10-19T17:07:03.217441+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=young-badlands-22721.herokuapp.com request_id=15c692ce-0a72-4b01-8b55-6a65c777d69d fwd="82.74.147.203" dyno= connect= service= status=503 bytes= protocol=https
2021-10-19T17:07:19.270779+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=young-badlands-22721.herokuapp.com request_id=11d99186-6f7e-4cbb-be4c-8d6f553106f1 fwd="82.74.147.203" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by arielj** [comment]
This sample app is not using any database (it's just using the default sqlite gem but not really using the database for anything), if you want to deploy it to heroku make sure you don't use the postgresql addon since it doesn't really use a db. Something is trying to install postgres but it's not this app's code
